from enum import Enum


class EventType(Enum):
    """
    All the possible Event Types
    """
    UNKNOWN = 0
    INDUSTRY_OUTPUT = 1
    INDUSTRY_EMPLOYMENT = 2
    INDUSTRY_EMPLOYEE_COMPENSATION = 3
    INDUSTRY_PROPRIETOR_INCOME = 4
    COMMODITY_OUTPUT = 5
    LABOR_INCOME = 6
    HOUSEHOLD_INCOME = 7
    INDUSTRY_SPENDING_PATTERN_2018 = 8
    INDUSTRY_CONTRIBUTION_ANALYSIS = 20
    INSTITUTIONAL_SPENDING_PATTERN_2018 = 30
    INDUSTRY_SPENDING_PATTERN_2019 = 9
    INDUSTRY_IMPACT_ANALYSIS = 10
    INSTITUTIONAL_SPENDING_PATTERN_2019 = 40
    INSTITUTIONAL_SPENDING_PATTERN = 11
    INDUSTRY_SPENDING_PATTERN = 12
    CUSTOM_SPENDING_PATTERN = 13
    HOUSEHOLD_SPENDING_PATTERN = 14
    INTERNATIONAL_INDUSTRY_IMPACT_ANALYSIS = 15
    CUSTOM_INDUSTRY_IMPACT_ANALYSIS = 16
    CUSTOM_INTERNATIONAL_INDUSTRY_IMPACT_ANALYSIS = 17


class SpendingPatternValueType(Enum):
    """
    The different Spending Pattern Value Types
    """
    INTERMEDIATE_EXPENDITURE = 0
    OUTPUT = 1

class MarginType(Enum):
    PRODUCER_PRICE = 0
    PURCHASER_PRICE = 1